export interface InsegnUgovInterface {
    coper_id: number;
    dip_des: string;
    nome_cds: string;
    aa_off_id: string;
    af_gen_cod: string;
    af_gen_des: string;
    sett_cod: string;
    sett_des: string;
    peso: string;
    des_tipo_ciclo: string;
    matricola: string;
    cognome: string;
    nome: string;
    sesso: string;
    cod_fis: string;
    ruolo_doc_cod: string;
    coper_peso: string;
    ore: number;
    data_ini_contratto: string;
    data_fine_contratto: string;
    compenso: string;
    tipo_coper_cod: string;
    tipo_atto_des: string;
    tipo_emitt_des: string;
    motivo_atto_cod: string;
    numero: string;
    data: string;
}
